export const ACTIONS={
    FETCH_DATA_START:"FETCH_DATA_START",
    FETCH_DATA_SUCCESS:"FETCH_DATA_SUCCESS",
    FETCH_DATA_FAIL:"FETCH_DATA_FAIL",
    DETECT_HAND_START:"DETECT_HAND_START",
    DETECT_HAND_SUCCESS:"DETECT_HAND_SUCCESS",
    DETECT_HAND_FAIL:"DETECT_HAND_FAIL",
    CLEAR_DETECT_HAND_RESULT:"CLEAR_DETECT_HAND_RESULT"
}